name: Deploy
on: push
jobs:
    lin-project:
        runs-on: ubuntu-latest
        steps:
            - name: run lint
              run: npm lint
    test-project:
        needs: lin-project
        runs-on: ubuntu-latest
        steps: 
            - name: run test
              run:
    deploy-project:
        needs: test-project
        runs-on: ubuntu-latest
        steps:
            - name: run deploy
              run: echo "deploying..."